import cv2
img = cv2.imread('table1.png',0)
_, th1= cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
th2 = cv2.adaptiveThreshold(img, 255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 11,2)
th3 = cv2.adaptiveThreshold(img, 255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11,2)
contours, hierarchy = cv2.findContours(th2,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
print("Number of countors =" +str(len(contours)))
print(contours[0])
cv2.drawContours(th2,contours,0,(0,255,0),3)
cv2.imshow('image',img)
cv2.imshow("Image",th3)
cv2.imshow("TH2",th1)
cv2.waitKey()
cv2.destroyAllWindows()